<x-layouts.app heading="Action Outcomes">
    <section class="rounded-lg bg-navy p-6 text-white shadow-[0_18px_50px_rgba(5,18,55,0.22)]"><p class="text-xs font-bold uppercase tracking-[.18em] text-teal-200">Measured follow-through</p><h2 class="mt-2 text-2xl font-bold">Marketing Action Outcomes</h2><p class="mt-2 max-w-3xl text-sm text-slate-300">Compare equivalent periods after completed agent work. Results indicate association, not guaranteed causation.</p></section>
    <form method="GET" class="mt-5 grid gap-3 rounded-lg bg-white p-4 shadow-[0_0_0_1px_rgba(5,18,55,0.06)] sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">
        <select name="website_id" class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="">All workspaces</option>@foreach($websites as $website)<option value="{{ $website->id }}" @selected(request('website_id') == $website->id)>{{ $website->name }}</option>@endforeach</select>
        <select name="agent_id" class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="">All agents</option>@foreach($agents as $agent)<option value="{{ $agent->id }}" @selected(request('agent_id') == $agent->id)>{{ $agent->name }}</option>@endforeach</select>
        <select name="status" class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="">All statuses</option>@foreach(['waiting','improved','no_change','declined','inconclusive','failed'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str_replace('_',' ',ucfirst($status)) }}</option>@endforeach</select>
        <select name="conversion_goal" class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="">All goals</option>@foreach($conversionGoals as $goal)<option value="{{ $goal }}" @selected(request('conversion_goal')===$goal)>{{ str_replace('_',' ',ucfirst($goal)) }}</option>@endforeach</select>
        <select name="evaluation_type" class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="">All evaluation types</option>@foreach(['page','query','conversion_goal'] as $type)<option value="{{ $type }}" @selected(request('evaluation_type')===$type)>{{ str_replace('_',' ',ucfirst($type)) }}</option>@endforeach</select>
        <input type="date" name="date_start" value="{{ request('date_start') }}" class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><input type="date" name="date_end" value="{{ request('date_end') }}" class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm">
        <div class="flex gap-2 sm:col-span-2 lg:col-span-4 xl:col-span-7"><button class="min-h-10 rounded-lg bg-teal px-4 text-sm font-semibold text-white">Apply filters</button><a href="{{ route('action-outcomes.index') }}" class="inline-flex min-h-10 items-center rounded-lg border border-slate-200 px-4 text-sm font-semibold">Reset</a></div>
    </form>
    <section class="mt-6 grid gap-4">@forelse($outcomes as $outcome)<a href="{{ route('action-outcomes.show',$outcome) }}" class="block rounded-lg bg-white p-5 shadow-[0_0_0_1px_rgba(5,18,55,0.06),0_14px_34px_rgba(5,18,55,0.07)]"><div class="flex flex-wrap items-start justify-between gap-3"><div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-teal/10 px-2.5 py-1 text-xs font-semibold text-teal">{{ str_replace('_',' ',ucfirst($outcome->evaluation_type)) }}</span><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{{ str_replace('_',' ',ucfirst($outcome->status)) }}</span>@if($outcome->confidence)<span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-800">{{ ucfirst($outcome->confidence) }} confidence</span>@endif</div><h2 class="mt-3 text-lg font-bold text-navy">{{ $outcome->agentAction->title }}</h2><p class="mt-1 text-sm text-slate-500">{{ $outcome->website->name }} &middot; {{ $outcome->agentAction->run->agent->name }}</p></div><i data-lucide="arrow-right" class="size-5 text-teal"></i></div><p class="mt-3 text-sm leading-6 text-slate-600">{{ $outcome->outcome_summary ?: 'Waiting for a complete post-action comparison period.' }}</p><div class="mt-4 grid gap-2 text-xs text-slate-500 sm:grid-cols-2"><p>Baseline: {{ $outcome->baseline_start?->format('M j, Y') ?? '--' }} - {{ $outcome->baseline_end?->format('M j, Y') ?? '--' }}</p><p>Evaluation: {{ $outcome->evaluation_start?->format('M j, Y') ?? '--' }} - {{ $outcome->evaluation_end?->format('M j, Y') ?? '--' }}</p></div></a>@empty<div class="rounded-lg bg-white px-6 py-16 text-center"><i data-lucide="chart-no-axes-combined" class="mx-auto size-9 text-slate-300"></i><p class="mt-3 font-semibold text-navy">No measured outcomes yet</p><p class="mt-1 text-sm text-slate-500">Completing an agent-created task will capture its baseline automatically.</p></div>@endforelse</section><div class="mt-6">{{ $outcomes->links() }}</div>
</x-layouts.app>
